# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='billing_address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_profiles', to='profiles.BillingAddress'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to='companies.Company'),
        ),
    ]
