# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 21:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 11, 21, 45, 49, 940333, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
