# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 13:29
from __future__ import unicode_literals

import companies.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20170812_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(default=None, help_text='Will be used for validation purpose. If not provided, then validation will be avoided', max_length=255, null=True, verbose_name='Domain Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(upload_to=companies.services.CompanyService.get_file_path, verbose_name='Company Logo'),
        ),
    ]
