# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 11:20
from __future__ import unicode_literals

import companies.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20170812_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='short_description',
            field=models.CharField(default=None, help_text='Short Description', max_length=800, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(upload_to=companies.services.CompanyService.get_file_path, verbose_name='Company Logo'),
        ),
    ]
