# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 12:03
from __future__ import unicode_literals

import companies.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20170812_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(upload_to=companies.services.CompanyService.get_file_path, verbose_name='Company Logo'),
        ),
    ]
